[package]
name = "lc-prompts"
version = "0.14.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Prompt templates for langchainrust"
repository = "https://github.com/atliliw/langchainrust"
rust-version = "1.82"

[dependencies]
lc-schema = { path = "../lc-schema", version = "0.14.0" }

[features]
default = []
wasm = []

[package.metadata.docs.rs]
all-features = true
